name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # Wait for a while to let the deployment process start
          sleep 120

          # Check deployment status
          DEPLOY_STATUS=$(curl -s -X GET \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID | jq -r '.service.status')

          echo "Deployment status: $DEPLOY_STATUS"

          # Fail if deployment is not successful
          if [ "$DEPLOY_STATUS" != "live" ]; then
            echo "Deployment failed"
            exit 1
          fi
