name: RSpec Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.PG_CI_TEST_INFO }}
          POSTGRES_USER: ${{ secrets.PG_CI_TEST_INFO }}
          PGPASSWORD: ${{ secrets.PG_CI_TEST_INFO }}
        ports:
          - 5432:5432
        # サービスコンテナが起動するのを待つためのオプション
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0 # プロジェクトに合わせてRubyのバージョンを指定

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          gem install bundler
          bundle install
      - name: Setup Database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: ${{ secrets.PG_CI_TEST_INFO }}
          PGPASSWORD: ${{ secrets.PG_CI_TEST_INFO }}
          POSTGRES_DB: ${{ secrets.PG_CI_TEST_INFO }}
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run RSpec
        run: bundle exec rspec
