name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    name: Run Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "This is Workflow 2"
