name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Run Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "This is Workflow 1"
